name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  runCodeQualityChecks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependecies
        run: npm ci

      - name: Format code using Prettier
        run: npm run format

      - name: Lint source code
        run: npm run lint

  # TODO: Run test suite

  runNextBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies for Next.js Build
        run: npm ci

      - name: Run Next.js build to generate the static files
        run: npm run build

        # Runs the deploy command
      - name: 🚀Deploy
        id: deploy-netlify
        run: netlify deploy --build --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
